- Makefile
- README.md
1. Updated README with more detailed instructions how to set up and run `director`
2. Removed obsolete information about setting up folders for shared secrets (between the roles).
3. Removed obsolete commands in Makefile:
* not using `bjoern` (replaced by `gunicorn`) any more so `libev` installation is not needed
* shared secrets folders etc not needed any more (see 2 above)
> README update and removed obsolete commands in Makefile

- director/projects/disk_file_facade.py
- director/projects/management/commands/pull_all_projects.py
- director/projects/project_models.py
- director/projects/project_puller.py
- director/projects/project_views.py
- director/projects/source_edit.py
- director/projects/source_forms.py
- director/projects/source_item_models.py
- director/projects/source_models.py
- director/projects/source_operations.py
- director/projects/source_views.py
- director/projects/templates/projects/filesource_create.html
- director/projects/templates/projects/project_files.html
- director/projects/templates/projects/project_overview.html
- director/projects/templates/projects/source_update.html
- director/projects/templatetags/source_extras.py
- director/projects/urls.py
@nokome Appreciate this is a big change and you're quite busy but it would be good if you just gave it a once over.
There is no way to create new `FileSource`s except for in the ProjectRefresh which will soon be deprecated.
I have created a Django command that needs to be run after this code is deployed to pull every project's virtual files to disk.
> feat: Uploads now go direct to disk and FileSources are redundant.

- director/accounts/templates/accounts/account_list.html
- director/assets/css/stencila.css
- director/assets/css/styles.css
- director/assets/js/delete-confirm-modal.js
- director/assets/sass/form/elements/_submit-button.sass
- director/assets/sass/imports/_overrides.sass
- director/assets/sass/overrides/_button.sass
- director/assets/sass/overrides/_typography.sass
- director/assets/sass/styles.sass
- director/package-lock.json
- director/package.json
- director/projects/templates/projects/project_archives.html
- director/projects/templates/projects/project_files.html
- director/projects/templates/projects/project_list.html
- director/projects/templates/projects/project_overview.html
- director/templates/_header.html
- director/templates/base.html
- director/users/templates/beta_token.html
- director/users/templates/users/signin.html
- director/users/templates/users/signout.html
Related to https://github.com/stencila/style/pull/7.
* **fix(signout, signin, beta_token, header, modal):** aligning button styles with stencila brand guidelines (blue rounded buttons) + using three-quarters-sized columns instead of half-sized columns.
* **fix(account_list, project_list, project_archives, project_overview, base):** using columns in base and project_archives. Using section--inner class for project_overview, project_list, and account_list. Aligning buttons and listed items with branding guidelines in account_list, project_list. Using box instead of card.
* **fix(buttons, anchors):** Aligning hub submit button styles with call-to-action. Removing text decoration from buttons. Making sure anchors are underlined/bolded for appropriate elements (not in box, call-to-action, or …
> Hub UI tweaks: section--inner spacing, column sizes, button/anchor alignment, box usage

- director/assets/sass/atoms/_tooltip.sass
- director/assets/sass/styles.sass
- director/stencila_open/templates/open/main.html
- director/stencila_open/views.py
- director/templates/_header.html
fix(Open Main):
- Update landing page tagline
- Make tooltips more symmetrical between enter URL/upload file options
- Make tooltips mobile friendly
- Remove example links, add section with icon placeholders for future screenshots
fix(Open Icon): Fix Jupyter icon on Open Output
**Updated landing (desktop)**
**Updated landing tooltips (mobile)**
**Updated landing examples (mobile)**
**Updated URL tooltip content (desktop)**
**Updated file upload tooltip content (mobile)**
> fix(Open): Landing page updates

- director/assets/css/styles.css
- director/assets/sass/atoms/_tooltip.sass
- director/stencila_open/templates/open/main.html
Basic UX fixes for tooltips, removed the href="#" link so they don't cause jumpin' around on mobile.
@alex-ketch I still wasn't sure about your references to `:focus` for screen readers? I added another selector to line 6 on `director/assets/sass/atoms/_tooltip.sass`. Is this what you meant?
> fix: Improve tooltip UI to not jump around on mobile

- director/assets/sass/styles.sass
- director/stencila_open/templates/open/main.html
* added space between main heading and tagline
* display URL and upload options side-by-side
Updated desktop landing:
---
> fix(Landing Page): Make URL and upload options side-by-side

- director/assets/css/styles.css
- director/assets/sass/overrides/bulma/_navbar.sass
- director/assets/sass/styles.sass
- director/stencila_open/templates/open/_more_dropdown.html
- director/stencila_open/templates/open/_open_mobile_modals.html
- director/stencila_open/templates/open/_theme_dropdown.html
- director/stencila_open/templates/open/open_header.html
- director/stencila_open/templates/open/output.html
- director/stencila_open/views.py
- director/templates/_header.html
Made the /open navbar for mobiles into its own navbar, made a burger on the existing one, and the actions are all in modals now.
> chore: Refactor mobile /open menus

- director/projects/source_views.py
This avoid the following error when converting from a linked URL source to a Google Doc:
```bash
ERROR 2020-01-14 01:28:02,102 log 25198 Internal Server Error: /projects/4/files/convert/
Traceback (most recent call last):
File "/home/nokome/stencila/source/hub/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
response = get_response(request)
File "/home/nokome/stencila/source/hub/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
response = self.process_exception_by_middleware(e, request)
File "/home/nokome/stencila/source/hub/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File …
```
> fix(ConverterMixin): Check for file before removing

- director/scripts/create_dev_accounts.py
- director/scripts/create_dev_projects.py
Names for `Account` and `Project` now need to be slugs.
> chore: Fix names for model instances in development db

- director/accounts/templates/accounts/account_access.html
This uses the `.tooltip` classes as on the `/open` page. I struggled to get it to look OK on mobile. Maybe worth putting effort into the tooltip CSS / markup convention to make it usable in various contexts or see if there is a Bulma / Buefy extension for that.
> fix: Move help text into a tool tip to make page less busy

- director/projects/project_admin.py
- director/scripts/create_dev_users.py
- director/settings.py
- director/templates/500.html
- director/users/admin.py
- director/users/apps.py
This is done with the view to us `is_staff` users using the Django admin interface more to manage issues (e.g. duplicate accounts, project settings etc) without having to log in as a super user. It removes some of the risks associated with making changes to user instances.
> Restrict staff capabilities on admin site

- director/projects/api/views/nodes.py
- director/urls_api.py
Just noticed these when I was looking around, thought I'd quickly fix.
Renamed the variable `node_type` inside the `node_type` function. It's not good to shadow outer names inside a function. I would have preferred to rename the function to `get_node_type` for "function is verb" naming style but that would have been a much bigger change, so I did not. I also wanted to keep it consistent with the naming of the typescript implementation.
We do include `stencila.schema` as a requirement so this function could be implemented there for consistency.
I also updated the use of `isinstance` as it can take a list/tuple as its second arg and returns true if the value is any of those types.
Also fixed a couple of typos.
> chore: typo fixes and node_type refactor

- .config
- broker/Dockerfile
- broker/README.md
- director/lib/constants.py
- director/requirements.txt
- director/settings.py
- director/urls.py
- docker-compose.yaml
- monitor/Dockerfile
- monitor/Makefile
- monitor/README.md
- monitor/prometheus.yml
- router/Makefile
- router/entrypoint.sh
- router/nginx.conf
As the `monitor/README.md` says...
The `monitor` is the Hub's application monitoring service. It collects and stores metrics on the health of the other services in the Hub (and on its self). Time series of these metrics can be queried and displayed.
We use [Prometheus](https://prometheus.io/), a popular open-source application monitoring project orignally developed at SoundCloud.
Other services use so called "exporters" to expose metrics that Prometheus periodically scrapes, usually from the `/metrics` endpoint. For example, the `director` uses the `django_prometheus` Python package as an exporter and the `broker` uses the `rabbitmq_prometheus` plugin.
Prometheus exposes a simple tool for visualization of metrics at http://localhost:9090/graph. For example, a [graph of the `up` metric for …
> Add monitor service

- director/Makefile
- overseer/Makefile
- scheduler/Makefile
- worker/.flake8
- worker/Makefile
- worker/jobs/pull/elife.py
- worker/jobs/pull/elife_test.py
- worker/requirements.txt
Just exercising the pull request workflow, the pull job is still completely untested from the director side.
> Pull eLife job

- manager/manager/static/sass/styles.scss
- manager/users/api/views/users.py
- manager/users/api/views/users_tests.py
- manager/users/templates/users/_search.html
- manager/users/templates/users/_search_results.html
This adds a user search field intended to replace the Buefy based one [here](https://github.com/stencila/hub/blob/master/director/assets/js/user-search.js). This is not a high priority (although we do need it for teams and project members) but was done now as a spike to see how well an approach using `htmx` and HTML API responses would work for this more complicated use case.
I'm pretty happy with how quick it was to implement this. Although it could do with some tweaks to the UX. You can try it out standalone at http://localhost:8000/stencila/render/?wrap=users/_search.html
> feat(Manager): Add a user search

- manager/manager/static/sass/styles.scss
- manager/projects/templates/projects/sources/_sources.html
- manager/scripts/create_page_snaps.py
- fix(CSS): Reduce icon size for is-small-mobile controls
- feat(Sources): Hide source filter until working
- fix(Snaps): Avoid breaking element styles
- Some generated screenshots were mangling the elements being captured (namely toggle component). Was there a reason for adding the `margin/padding: -7px` CSS @nokome? The screenshots generated with these changes in this PR  seem to look good
> Manager: misc refinements

- manager/accounts/templates/accounts/update.html
- manager/manager/static/sass/styles.scss
- manager/manager/templates/base.html
- manager/projects/templates/projects/_project_list_item.html
- manager/projects/templates/projects/retrieve.html
- manager/projects/templates/projects/sharing.html
- manager/projects/templates/projects/sources/upload.html
- fix(Dropdowns): Keep dropdown menus in-line on touch breakpoints
- fix(CSS): Fix vertical scroll for sidebar menus on mobile breakpoints
- fix(Projects): Give project title and icons space when line wraps
- fix(Projects): Align sharing view title and toggle
- fix(Projects): Fix project view CTA buttons missing border bottoms
- fix(CSS): Fix styling of file upload forms on mobile (they are now vertically stacked on mobile)
- feat(Nav): Move "New X" buttons under respective Projects/Orgs nav items (Screenshot attached).
- The dropdown and the arrows are removed for anonymous users
> Misc manager refinements

- manager/manager/static/sass/projects/index.scss
- manager/manager/static/sass/projects/sources/index.scss
- manager/projects/templates/projects/snapshots/_list.html
`overflow: hidden` doesn't work for table-row elements causing the row link to take on the size of the full table, so disabling this until a workaround can be added.
> fix(Projects): Temporarily disable table row links due to bug

- manager/projects/models/sources.py
- manager/users/socialaccount/tokens.py
- worker/jobs/pull/gdoc.py
- worker/jobs/pull/gdoc_test.py
- worker/jobs/pull/gdrive.py
- worker/jobs/pull/github.py
- worker/jobs/pull/github_test.py
Previously we raised an exception if there was no auth token for a source (as is usually the case in development). This PR defers that exception raising to the worker, for example so that it can try to get a public Github repo without a token instead of always failing. This is also advantageous in that it makes job error handling more uniform.
This means more of the demo sources can be pulled, but also that occasionally an (expected) Github rate limit error will happen.
> Change the way that missing tokens are handled

- manager/manager/static/sass/projects/index.scss
- manager/manager/static/sass/styles.scss
- manager/manager/templates/_page_action_bar.html
- manager/projects/templates/projects/_assets_empty_state.html
- manager/projects/templates/projects/_new_asset_menu.html
- manager/projects/templates/projects/_project_hero.html
- manager/projects/templates/projects/base.html
- manager/projects/templates/projects/files/_list.html
- manager/projects/templates/projects/files/list.html
- manager/projects/templates/projects/jobs/_action_bar.html
- manager/projects/templates/projects/jobs/_job_item.html
- manager/projects/templates/projects/jobs/_list.html
- manager/projects/templates/projects/sharing.html
- manager/projects/templates/projects/snapshots/_action_bar.html
- manager/projects/templates/projects/snapshots/_list.html
- manager/projects/templates/projects/snapshots/list.html
- manager/projects/templates/projects/sources.html
- manager/projects/templates/projects/sources/_source_actions_menu.html
- manager/projects/templates/projects/sources/_sources.html
- manager/projects/templates/projects/sources/_status_type_icon.html
- manager/projects/ui/views/projects.py
- feat(Sources): Add header and info to Sources list
- feat(Projects): Use Files list as default view for Projects
- fix(Jobs): Animate Dispatched status icon
- fix(Projects): Use different icons for Files & Sources
- feat(Projects): Add empty state views to Files/Sources, extract partials
- fix(Jobs): Refine Job list styles and fix Job ID causing breaking layout
- fix(Projects): Standardize sub-page layouts, icons
- feat(Projects): Move Snapshot button to be closer to files
---
Two future TODOs were added in this PR:
- https://github.com/stencila/hub/pull/521/files#diff-45fbabe372f0920b325bda8c6c7f6658R20
- https://github.com/stencila/hub/pull/521/files#diff-cfc165a6709b033ced1d550cdfb11902R31
> Project Files/Sources refinements

- manager/manager/static/sass/projects/index.scss
- manager/manager/static/sass/styles.scss
- manager/projects/templates/projects/jobs/_job_item.html
- manager/projects/templates/projects/jobs/_job_list.html
- manager/projects/templates/projects/jobs/_list.html
- manager/projects/templates/projects/jobs/_retrieve.html
When viewing a Job, this PR exposes the nested sub-Jobs inline to allow better comprehension of what's going on as well as easier identification of any errors.
There are further refinements which should be made around the top level information presented, links to parent Jobs when viewing a sub-Job, etc. but I feel these are best deferred till we get some real usage data and have time for design iterations.
Preview attached below:
> feat(Jobs): Expose sub-jobs in line with parent Job

- manager/manager/static/js/src/dropdowns.js
This PR adds an event lister to dropdown menus to open them on `click` events.
This functionality is needed to program the Intercom Product Tours for features contained in dropdown menus.
> Open dropdown menus for click events

- manager/accounts/templates/accounts/plan.html
Fixes horizontal layout when multiple tiers are available.
More refinements will be made in a future PR for addressing logic around which options should be shown to users (should we prevent `Waiting List` candidates from paying to upgrade their account? I suggest not), and need to add listing for Publisher/Enterprise account.
**Before**
**After**
> fix(Accounts): Fix Plan Tier listing layout overflow

- manager/manager/static/js/src/buttons.js
Previously if a form failed a browser native validation, the button would remain spinning indefinitely.
This fixes the issue by listening for an `oninvalid` event on all of the form's `input` fields.
> Reset spinner buttons if Form contains an error

- manager/README.md
- manager/accounts/models.py
- manager/manager/api/helpers.py
- manager/manager/helpers.py
- manager/manager/paths.py
- manager/manager/settings.py
- manager/manager/templates/base.html
- manager/projects/admin.py
- manager/projects/api/serializers.py
- manager/projects/api/views/projects.py
- manager/projects/migrations/0004_add_project_temporary.py
- manager/projects/models/projects.py
- manager/projects/models/sources.py
- manager/projects/paths.py
- manager/projects/templates/projects/_claim_form.html
- manager/projects/templates/projects/base.html
- manager/projects/templates/projects/claim.html
- manager/projects/templates/projects/messages/temporary_project.html
- manager/projects/templates/projects/open.html
- manager/projects/templates/projects/update.html
- manager/projects/ui/urls.py
- manager/projects/ui/views/files.py
- manager/projects/ui/views/messages.py
- manager/projects/ui/views/projects.py
- manager/projects/ui/views/sources.py
- manager/scripts/create_dev_db.py
Before deprecating the `director` completely I wanted to check out how easily we could  reimplement `/open` in `manager`, including the notion that a `/open` "conversion" is just one way to kick start a project, including for anonymous users, by providing a "wizard" to make a particular source the "main" project file. 
Towards that, this PR:
This is a very initial, bare bones page, needs to go towards existing `/open` page
I envisage the user gets redirect to a very simple "in progress" page - a simple message and a progress bar, with a redirect to the next page below when the job is complete.
I think we should keep the steps 2 and 3 (preview and "final") page of the existing `/open` but they will be something like "project theme selector" and "project overview" pages rather than `/open` …
> Reinstate /open

- manager/Makefile
- manager/manager/static/js/src/libs.js
- manager/manager/templates/base.html
- manager/users/templates/users/signout.html
After splitting JS files into two, the 3rd party libraries are exposed using a `managerLibs` object instead of simply `manager`.
> Fix JS usage after splitting into multiple files

- manager/accounts/templates/accounts/list_orgs.html
- manager/manager/templates/base.html
- manager/projects/templates/projects/snapshots/_list.html
- fix(Orgs): Don't attach event handler if role dropdown doesn't exist (Close #560)
- feat(UI): Add links to Help docs & open links in new tabs
- docs(Snapshots): Finish trailing sentence in empty state message
> Misc fixes and refinements

- manager/accounts/api/serializers.py
- manager/accounts/api/views.py
- manager/accounts/models.py
- manager/accounts/templates/accounts/_update_profile_fields.html
A user's first and last names are stored on Django's built-in user model and were previously only visible via the admin interface e.g.
Currently, when a user signs up, they are not able to set first or last names and these fields only get populated via social auth (e.g. we get first and last name if someone signs up via Google).
This PR makes a couple of improvements:
- for personal accounts, a user can change their first and last name using the account profile form (for organisational accounts they can edit the "display name")
- when a user signs up, or when they change their first or last name using the account profile form, the `display_name` of their `personal_account` gets updated
@colettedoughty ccing you in here because some changes to documentation may be warranted.
> fix(User profiles): Allow setting of first and last names

- manager/manager/static/sass/projects/index.scss
- manager/manager/static/sass/projects/sources/index.scss
- manager/manager/static/sass/styles.scss
- manager/users/api/views/users.py
- manager/users/templates/users/_search.html
- manager/users/templates/users/_search_results.html
This adds user image and other public identifying information to the user search results to make it easier to identify the correct user when adding them to the project.
@alex-ketch Could you finish off the styling of the results. They currently look like this.
I envisaged to lines of text to the right of the image: top line has username and other name, bottom line has any other information that might be useful to display e.g. email, location, affiliation etc
Also probably a good time to look at improving the UX of selecting the user - highlight on hover etc.
> User search

- manager/projects/api/views/snapshots.py
With the upcoming fixes in Designa PR https://github.com/stencila/designa/pull/74, the following will no longer be necessary.
Can be currently tested be replacing the Designa UNPKG version in the Snapshot to point to the `@next` version.
> fix(Snapshots): Don't inject CSS variables as they're set by Designa

- manager/projects/api/views/snapshots.py
This ensures that any CSS variables defined in the Thema theme are inherited by the Toolbar.
There's probably a less brittle way of finding the `data-itemscope="root` `article` element, but this works for now.
Please feel free to improve if you can @nokome, thanks!
> Inject Executable Toolbar into Thema article context

- clients/typescript/package.json
- clients/typescript/tsconfig.prod.json
Currently the TypeScript Hub Client's `main` entry file path doesn't resolve, causing errors when trying to use the package.
This is due to: `main": "./dist/index.js"`, however the published package file is at `dist/src/index`.
This PR fixes the the above issue, while at the same time avoiding the inclusion of test files in the published package.
---
**[Current package folder structure](https://unpkg.com/browse/@stencila/hub-client@3.41.0/dist/)**
> fix(TS Client): Fix packaging of TypeScript client

- manager/users/api/serializers.py
- manager/users/api/views/users.py
- manager/users/api/views/users_tests.py
- allows a user to be retrieved by id or username
- adds personal account fields including image responses for `GET /users/{user}`
- adds additional fields including email addresses and linked external accounts to  `GET /users/me`
```json
{
"dateJoined": "2020-10-06T02:10:43.359168Z", 
"displayName": "Dr Anna Andersson", 
"emailAddresses": [
{
"email": "anna@example.edu", 
"primary": true, 
"verified": true
}, 
{
"email": "anna.andersson@example.com", 
"primary": false, 
"verified": false
}
], 
"firstName": "Anna", 
"id": 8, 
"image": {
"large": "http://localhost:8000/local/media/__processed__/971/anna_WqQyX1C-a1a0071d4063.png", 
"medium": "http://localhost:8000/local/media/__processed__/971/anna_WqQyX1C-5b678ba0c304.png", 
"small": …
```
> API: Add more data to /users reponses

- manager/.gitignore
- manager/accounts/ui/views/content.py
- manager/manager/static/js/src/errorHandler.js
- manager/rollup.config.js
This is a simple attempt to handle errors which can occur when reading an executable article.
The handler attempts to reload the article once, showing a message to the user if it continues to fail.
> Attempt to handle WebComponent loading errors

- manager/accounts/templates/accounts/_update_user_settings.html
- manager/accounts/templates/accounts/update.html
- manager/manager/settings.py
- manager/manager/templates/base.html
- manager/manager/testing.py
- manager/manager/urls_tests.py
- manager/users/admin.py
- manager/users/api/urls.py
- manager/users/api/views/features.py
- manager/users/api/views/features_tests.py
- manager/users/migrations/0002_flags.py
- manager/users/migrations/0004_features.py
- manager/users/models.py
- manager/users/templates/users/features.html
- manager/users/ui/urls.py
- manager/users/ui/views.py
After discussing with @alex-ketch the need for allowing users to turn off things like product analytics, I realized that this could be fairly easily implemented using our existing `waffle`-based feature flags (which is good because that already does a things like caching, setting up the models etc).
Features, including those with privacy implications, can be set by users on a new `/me/features` page which is accessible from personal `/<account>/settings`:
- The `/me/features/` page has a description of the each feature and a toggle on/off. The `label` and `note` for these features flags are defined in `manager/users/migrations/0002_flags.py` but can be edited later via the admin (e.g. if we change external service provider for one of the features)
- The `/stencila/admin/users/flag/` page …
> Feature and privacy switches

- manager/manager/static/sass/projects/index.scss
Fixes math for the 3 column grid items to match the larger 2 column items.
> Project gallery: Fix 3 column grid item size

- manager/projects/templates/projects/_update_execution_form.html
Intercom help docs aren't served over HTTPS (right now?), and trying to visit the link shows a certificate error.
This "fixes" the issue.
> Fix link to Help documentation

- manager/accounts/ui/views/accounts.py
Related to https://github.com/stencila/hub/pull/880
The previous PR ensured plans were sorted for on `/pricing` view, but did not do so on the logged in user account view.
> fix(Pricing): Sort account plans for logged in users

- package.json
This PR updates the Renovate config to prefix `@stencila/thema` and `@stencila/component` package update commits with a `fix` keyword. This should trigger an automatic release cycle on the CI.
> Trigger release when auto-updating ERA dependencies

- manager/manager/static/sass/projects/index.scss
- manager/projects/templates/projects/jobs/_job_item.html
- Fix link to Job creator profile, previously it would point to the currently logged in user's profile instead of the account which triggered the job
- Fix styling of nested sub-jobs list to avoid a double left-border
> Fix job creator link & nested sub-job list styling

- manager/accounts/api/serializers.py
- manager/accounts/api/views.py
- manager/accounts/templates/accounts/users/_account_role_help_tip.html
- manager/accounts/templates/accounts/users/_list.html
- manager/accounts/templates/accounts/users/update.html
- manager/manager/api/helpers.py
- manager/manager/static/sass/styles.scss
- manager/manager/templates/_user_role_help_tip.html
- manager/projects/models/projects.py
- manager/projects/templates/projects/_agents_list.html
- manager/projects/templates/projects/_collaborator_role_help_tip.html
- manager/projects/templates/projects/sharing.html
- manager/projects/templates/projects/update.html
Close #709 
I was debating whether to place the tooltip closer to the current area of focus (the input fields), or move it to the section title (above the form, next to the `Collaborators` text). There is minor visual offset happening when the icon is placed next to the input field, however I felt that it would be the most helpful and discoverable there when a user is trying to add members.
Do you have any thoughts @nokome? Would also appreciate if you could look over and verify the role differences in the help text.
Thanks!
**Mobile**
> Add tooltip explaining differences between user roles

- manager/manager/static/sass/styles.scss
- manager/projects/templates/projects/sources/_create_googledrive_picker.html
We noticed that the File Picker would cause `400` errors if the browser did not have 3rd party cookies enabled.
The link leads to [Google known issues document](https://developers.google.com/identity/sign-in/web/troubleshooting#third-party_cookies_and_data_blocked) which mentions possibility of making an exception for `accounts.google.com` domain.
Do you think it's necessary to create a standalone help article of our own at this time @nokome?
> Mention 3rd party cookie requirement for adding Google sources

- manager/manager/templates/base.html
- manager/projects/templates/projects/jobs/_progress_buttons.html
- Updates the header logo link to direct signed in users to the Hub root page, and anonymous users to the marketing site. This helps reduce confusion for signed in users as on the marketing site we don't share the signed-in state, and all users are shown the `sign in`/`sign -up` buttons
- To make the help resources more discoverable, signed in users will now see a dedicated "Help" item in the nav bar. If the deployment has a Userflow key, we also show a `In app guides` link which triggers the `Get started` checklist.
- File conversion progress bar will now always fill to 100% on job completion/error. I've also removed the dual actions for "Finished" + "Back" and only show a single "Go back" button when the job is finished.
https://user-images.githubusercontent.com/1646307/110685986-daca968 …
> Misc UX and quality of life refinements

- manager/accounts/api/views.py
- manager/accounts/templates/accounts/users/_list.html
- manager/manager/templatetags/stencila.py
Comments:
- the user name "Daniel" in the user list seemed to not sort correctly (believe it could be an issue with how it is saved? all others seemed to order correctly) 
- when I create a new test user it seems to also order them at the bottom (also could be related to how the data is saved for new accounts?) 
- Overall seems to sort as required
> fix(Manager): Fix users not being sorted alphabetically
