stencila/hub

- director/accounts/forms.py
- director/accounts/templates/accounts/account_list.html
- director/accounts/urls.py
- director/accounts/views.py
- director/settings.py
- director/templates/error404.html
- director/templates/error500.html
- director/urls.py
- director/views.py
Modals like in https://github.com/stencila/hub/pull/67
To see it work, you need to change `DEBUG` to `False` in `settings` (otherwise it shows the error like before)
> Handling 500 and 404 errors

- director/accounts/models.py
- director/checkouts/models.py
- director/editors/models.py
- director/hosts/models.py
- director/lib/enum_choice.py
- director/projects/permission_models.py
- director/projects/project_models.py
- director/projects/session_models.py
- director/projects/source_models.py
- director/settings.py
- director/users/views.py
- director/views.py
Edit some docstrings in python files.
Address partially issue #123.
> Correct some docstrings

- director/assets/css/styles.css
- director/assets/sass/styles.sass
- director/stencila_open/templates/open/main.html
Reposition examples to be more prominent on the landing page
> chore(Open): Reposition example document links

- Makefile
- director/.gitignore
- director/accounts/templates/accounts/account_access.html
- director/assets/js/filebrowser.js
- director/projects/templates/projects/_project_event_table.html
- director/projects/templates/projects/project_create.html
- director/projects/templates/projects/project_sharing.html
- director/projects/templates/projects/source_open.html
- director/settings.py
- director/stencila_open/templates/open/output.html
- director/templates/base.html
- package-lock.json
- package.json
A PR to remove unused JS and CSS dependencies and update others. Won't make any changes to the compiled (an committed) `director/assets` but may be removing redundant script tags in HTML templates.
> Javascript & CSS dependencies

- README.md
The title pretty much covers it 😇
> docs(README): Update make command documentation

- director/lib/conversion_types.py
- director/lib/converter_facade.py
- director/stencila_open/templates/open/main.html
- director/stencila_open/templates/open/open_footer.html
- director/stencila_open/templates/open/open_header.html
- director/stencila_open/templates/open/output.html
- director/stencila_open/templates/open/output_intermediary.html
- director/stencila_open/views.py
- director/templates/_header.html
- director/tests/test_urls.py
- director/user_views.py
> Integrate and update /open

- director/settings.py
> fix: Using custom DRF handler only in prod

- worker/jobs/pull/base.py
- worker/jobs/pull/elife.py
- worker/jobs/pull/http.py
- worker/jobs/pull/http_test.py
Partial porting of changes from converter_facade
> Worker pull http

- manager/.gitignore
- manager/Makefile
- manager/README.md
- manager/manager/middleware.py
- manager/manager/settings.py
- manager/requirements-dev.txt
- manager/scripts/create_page_snaps.py
See instructions in README.md. Generates a `snaps/index.html` file with a big table of images in it...
> Add script for screenshotting pages

- manager/accounts/templates/accounts/create.html
- manager/manager/static/sass/styles.scss
- manager/manager/templates/base.html
- manager/projects/templates/projects/create.html
- manager/projects/templates/projects/sources/_sources.html
- fix(Nav): Fix link for creating a new organization
- feat(Accounts/Projects): Add header to "New x" views
- feat(Projects): Reorganize "New source" menu, add placeholder sources
> "New Source" dropdown re-structure & misc fixes

- manager/manager/static/sass/projects/index.scss
- manager/manager/static/sass/projects/sources/index.scss
- manager/manager/static/sass/styles.scss
- manager/projects/templates/projects/jobs/_job_item.html
- manager/projects/templates/projects/jobs/_list.html
- manager/projects/templates/projects/jobs/_retrieve.html
- manager/projects/templates/projects/jobs/summary/_job_summary.html
- manager/projects/templates/projects/jobs/summary/_pull_summary.html
- manager/projects/templates/projects/snapshots/_list.html
- manager/projects/templates/projects/snapshots/_retrieve.html
- manager/projects/templates/projects/sources/_retrieve.html
- manager/projects/templates/projects/sources/_source_list_item.html
- manager/projects/templates/projects/sources/_status_type_icon.html
- manager/projects/templates/projects/sources/retrieve.html
- manager/projects/ui/views/sources.py
Please see commit messages for a summary of the changes.
@nokome This is just a first pass and there's lots of room for improvement. Feel free to make adjustments as you see fit and we can review/discuss at a later date, thanks!
> Style Jobs and Snapshots view

- manager/jobs/models.py
- manager/projects/templates/projects/jobs/_job_item.html
The pluralisation needs more work but IMO this is good enough for now.
> fix(Jobs): Display formatted runtime

- README.md
- package-lock.json
- package.json
- perf.ts
- perf/index.ts
- tsconfig.json
⚠️ WIP
Currently this tests for:
- Loading the homepage
- Granting an auth token
- Validating the auth token
- 99% of requests complete under 1.5s
- Request error rate remains below 5%
---
To run:
1. install k6 (https://k6.io/docs/getting-started/installation)
2. Run a local instance of the Hub
3. run in terminal `k6 run -e USERNAME=username -e PASSWORD=password perf/index.ts`
> test(*): Add basic load testing configuration

- manager/users/templates/account/password_reset.html
- manager/users/templates/account/password_reset_done.html
- manager/users/templates/account/password_reset_from_key.html
- manager/users/templates/account/password_reset_from_key_done.html
> Style password reset form view

- manager/accounts/templates/accounts/content/404_invalid_file.html
- manager/accounts/ui/urls.py
- manager/accounts/ui/views/content.py
- manager/manager/settings.py
- manager/manager/storage.py
- manager/projects/api/views/snapshots.py
- manager/projects/models/files.py
- manager/projects/models/projects.py
- manager/projects/templates/projects/files/retrieve.html
- manager/projects/ui/urls.py
- manager/projects/ui/views/files.py
- manager/requirements.txt
- manager/scripts/create_dev_db.py
> Preview and serving of files in project working directory

- manager/accounts/templates/accounts/_plan_table_item.html
- manager/accounts/templates/accounts/_plans_beta_notice.html
- manager/accounts/templates/accounts/_plans_faq.html
- manager/accounts/templates/accounts/_plans_table.html
- manager/accounts/templates/accounts/plan.html
- manager/accounts/templates/accounts/plans.html
- manager/manager/paths.py
- manager/manager/static/sass/accounts/index.scss
- manager/manager/static/sass/styles.scss
- manager/manager/templates/base.html
- manager/manager/templatetags/stencila.py
- manager/manager/ui/views.py
- manager/manager/urls.py
- manager/projects/templates/projects/_project_description.html
Looking for feedback around:
- the language, especially around the Waiting List notices
- the contact method for enterprise plans. Currently it's a `mailto` trigger to hello@stenci.la
- the FAQ section, and what to add/reword
---
**Public/Anonymous user view**
---
**Signed in View (on waiting list)**
---
**Signed in View (_not_ on waiting list)**
> Updating pricing plans view & add public pricing page

- manager/jobs/models.py
- manager/manager/themes.py
- manager/package-lock.json
- manager/package.json
> Update queue message & Thema dependency

- manager/Makefile
- manager/manager/testing.py
- manager/projects/api/serializers.py
- manager/projects/api/views/projects.py
- manager/projects/api/views/projects_tests.py
- manager/projects/api/views/sources.py
- manager/projects/models/projects.py
- manager/projects/models/projects_tests.py
- manager/projects/models/sources.py
- manager/projects/models/sources_tests.py
Closes #705
Please see new API docs for projects:
Also, I have added some docs on how to add a source to a project using the API:
> Add project filtering fields

- manager/accounts/models.py
- manager/accounts/ui/views/accounts.py
- manager/manager/settings.py
- manager/manager/templates/base.html
- manager/projects/api/views/nodes.py
- manager/projects/api/views/nodes_tests.py
- manager/projects/models/nodes.py
- manager/projects/models/projects.py
- manager/projects/templates/projects/nodes/basic.html
- manager/projects/templates/projects/nodes/complete.html
- manager/projects/ui/views/files.py
- manager/projects/ui/views/jobs.py
- manager/projects/ui/views/projects.py
- manager/projects/ui/views/snapshots.py
- manager/projects/ui/views/sources.py
- manager/requirements.txt
Adds `<meta>` tags to `<head>` for pages for accounts, projects and nodes.
> feat(Meta data): Add meta data to pages for Accounts, Projects and Nodes.

- manager/accounts/templates/accounts/_plan_table_item.html
- manager/manager/ui/views.py
Close #770 
The updated design looks like so:
> fix(Pricing): Ensure Account plans are correctly ordered

- manager/manager/templates/serializers/_field.html
- manager/manager/templates/serializers/_field_control.html
Close #760 
Screenshot of updated styles
> Improve styling of form fields w/ errors

- manager/projects/api/views/sources.py
- manager/projects/templates/projects/jobs/_progress_buttons.html
- Fixes file conversion progress bar starting in an animated state
- Fixes #917: fetching of URL sources, based on https://stackoverflow.com/a/51196932/5686014
> Misc fixes

- worker/jobs/pull/cassettes/elife_test/test_ok.yaml
- worker/jobs/pull/elife.py
See https://github.com/stencila/encoda/issues/826
> eLife job: Fix errors when fetching low-res article graphics

- manager/manager/static/sass/projects/index.scss
- manager/manager/templates/_pagination.html
- manager/projects/templates/projects/jobs/_job_item.html
- manager/projects/templates/projects/jobs/_retrieve.html
See https://github.com/stencila/hub/issues/1016#issuecomment-779286369
To test this out with dev database, find the project with the most jobs:
```sql
sqlite3 dev.sqlite3
select project_id, count(*) as jobs from jobs_job group by project_id order by jobs desc;
```
Then navigate to http://127.0.0.1/projects/<project_id>/jobs logged in as `owner` (who has access to all projects as owner).
> fix(Pagination): Do not show all page links when many

- manager/projects/templates/projects/sources/_source_actions_menu.html
- manager/projects/templates/projects/sources/retrieve.html
> Projects: Hide Pull action for uploaded files
